# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5dd4fd43be4f9f80922849b9526cc603d0b4e57257126ea31eac3ababb9c8ae764072ad492ca3af06f359e4f2b8be54cf42ebe88a2ceb466b874fb629b214f4a

test:
  secret_key_base: afc31002ccdcb6ce030277dd952150de613a7fe72c5f760af295b2fb69c84f1c3c26da8f5acf9b1cbe769b0c7c4e04a3be4fdc29349c5fc1764e33586a208286

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
